version: '3.8'

services:

  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: prod
    env_file:
      - ../backend/.env
      - .infra-env
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000

  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: prod
    env_file:
      - .dockerenv_keys
      - .dockerenv_urls
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
  
