services:
  qdrant:
    container_name: vectorstore_qdrant
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../../../data/vectorstores/qdrant:/qdrant/storage